version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"