version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - drops_elasticsearch_data:/usr/share/elasticsearch/data
#  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:6.5.4
#    environment:
#      SERVER_NAME: localhost
#      ELASTICSEARCH_URL: http://elasticsearch:9200/
#    ports:
#      - "5601:5601"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - drops_grafana_data:/var/lib/grafana
  drops_agent:
    image: vantoozz/drops-agent
    ports:
      - "42345:42345/udp"
    environment:
      UDP_PORT: 42345
      STORAGE_DRIVER: elasticsearch
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_INDEX: drops
      BUFFER_MAX_SIZE: 9000
      BUFFER_FLUSH_INTERVAL_MS: 30000
      SENTRY_DSN: ${SENTRY_DSN}
volumes:
  drops_elasticsearch_data:
    driver: local
  drops_grafana_data:
    driver: local